###**PYTHON BASICS 2**

**Practice:** Let's find the sum of the numbers from one to one hundred.

In [ ]:
sum=0
for x in range(1,101):
  sum +=x
print(sum)

5050

In [ ]:
numbers = [13, 26, 33, 44, 59, 61, 72, 86, 90]
even_numbers = []
odd_numbers = []
for x in numbers:
  if not x%2:
    even_numbers.append(x)
  else:
    odd_numbers.append(x)
print(even_numbers)
print(odd_numbers)

[26, 44, 72, 86, 90]
[13, 33, 59, 61]

**Practice** Write a number guessing game.

In [ ]:
guess=31
counter=1
x = input("guess a number:")
while not x.isdigit():
  x=input("guess a number:")

while int(x)!=guess:
  if guess>int(x):
    print("wrong number please guess upper")
  else:
    print("wrong number please guess lower")
  x=input("guess a number")
  while not x.isdigit():
    x=input("guess a number")
  counter+=1
print("You guessed correctly after %d trials." %counter)

guess a number:98
wrong number please guess lower
guess a number31
You guessed correctly after 2 trials.

**Practice** Write a code in order to convert the Fahrenheit to the Celcius.

In [ ]:
attempts = 5
while attempts > 0:
  attempts -= 1
  x=input("enter a tempereture as fahrenheit: ")
  c= 5/9*(int(x)-32)
  if attempts == 0:
    break
  print(c,"Celcius")

enter a tempereture as fahrenheit: 32
0.0 Celcius
enter a tempereture as fahrenheit: 12
-11.11111111111111 Celcius
enter a tempereture as fahrenheit: 34
1.1111111111111112 Celcius
enter a tempereture as fahrenheit: 32
0.0 Celcius
enter a tempereture as fahrenheit: 234

**Practice** Create a list consist of fibonacci numbers from 1 to 50.

In [ ]:
x=0
y=1
i=2
fibonacci_list =[x,y]
while i<50:
  fibonacci=x+y
  fibonacci_list.append(fibonacci)
  x=y
  y=fibonacci
  i+=1
print(fibonacci_list)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733, 1134903170, 1836311903, 2971215073, 4807526976, 7778742049]

**Practice** Write a code that show entering number as a times table.

In [ ]:
numbers = list(range(11))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
times_table = input("enter a value: ")
for i in numbers: 
  print(times_table,"x", i, "=",i*int(times_table))

enter a value: 32
32 x 0 = 0
32 x 1 = 32
32 x 2 = 64
32 x 3 = 96
32 x 4 = 128
32 x 5 = 160
32 x 6 = 192
32 x 7 = 224
32 x 8 = 256
32 x 9 = 288
32 x 10 = 320

**Practice** Write a code that reverses the word which the user entered.

In [ ]:
x = input("enter a word: ")
print(x[::-1])

enter a word: new york
kroy wen

**Practice** Create a list of odd numbers from 1 to 20 squared, even numbers cubed.

In [ ]:
a = list(range(1,21,2))
print(a)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [ ]:
number_list = [i**2 for i in range(1,21,2)]+[x**3 for x in range(2,21,2)]
print(number_list)

[1, 9, 25, 49, 81, 121, 169, 225, 289, 361, 8, 64, 216, 512, 1000, 1728, 2744, 4096, 5832, 8000]